name: textsharer
description: to share text between devices.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  loading_animation_widget:
  uuid: ^3.0.6
  device_info_plus: ^9.0.2
  shared_preferences: ^2.1.2
  supabase_flutter: ^1.10.4
  flutter_dotenv: ^5.1.0
  network_info_plus: ^4.0.1
  connectivity_plus: ^4.0.1
  wifi_info_flutter: ^2.0.2
  permission_handler: ^10.3.0
  firedart: ^0.9.5
  dio: ^5.2.1+1
  flutter_native_splash: ^2.3.1
  quickalert: ^1.0.1
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - .env